pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '678878256416'
        IMAGE_NAME = 'project-ict'
        IMAGE_TAG = 'latest'
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main',
                url: 'https://github.com/msaadkhan54/Fast-Nu-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('project_ict') {
                    sh '''
                    docker build -t $IMAGE_NAME:$IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin \
                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                docker tag $IMAGE_NAME:$IMAGE_TAG \
                678878256416.dkr.ecr.us-east-1.amazonaws.com/ict_project:$IMAGE_TAG
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                docker push \
                678878256416.dkr.ecr.us-east-1.amazonaws.com/ict_project:$IMAGE_TAG
                '''
            }
        }
    }
}
