name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~
            rm -rf Fast-Nu-projects
            git clone https://github.com/YOUR_USERNAME/Fast-Nu-projects.git
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r Fast-Nu-projects/project_ict/* /usr/share/nginx/html/
            sudo systemctl restart nginx
