name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~

            # clean old repo
            rm -rf Fast-Nu-projects

            # IMPORTANT: correct repo URL
            git clone https://github.com/msaadkhan54/Fast-Nu-projects.git

            cd Fast-Nu-projects

            # clean nginx folder
            sudo rm -rf /usr/share/nginx/html/*

            # deploy correct folder (ONLY if it exists)
            sudo cp -r project_ict/* /usr/share/nginx/html/

            sudo systemctl restart nginx
